apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/Lucifergene/operator-stuffs/blob/main/shipwright/operator-group.yaml
- https://github.com/Lucifergene/operator-stuffs/blob/main/shipwright/subscription.yaml
- https://github.com/Lucifergene/operator-stuffs/blob/main/shipwright/shipwright-build.yaml